SELECT C_NAME, SUMA
FROM (SELECT C_CUSTKEY, C_NAME, SUM(O_TOTALPRICE) AS SUMA
		FROM CUSTOMER
		JOIN ORDERS ON O_CUSTKEY = C_CUSTKEY
		JOIN NATION ON C_NATIONKEY = N_NATIONKEY
		JOIN REGION ON R_REGIONKEY = N_REGIONKEY
		WHERE EXTRACT(YEAR FROM O_ORDERDATE) = 1997
			AND R_NAME = 'EUROPE'
		GROUP BY C_CUSTKEY)
WHERE SUMA > 500000
ORDER BY 1 DESC;